apply plugin: 'com.android.application'

// NDK version must match the ANDROID_NDK_VERSION env variable in .github/workflows/build.yml
def ndkVersionStr = "27.2.12479018"

android {
    namespace "com.mrmichel.rustdroid_emu"
    compileSdkVersion 36
    ndkVersion ndkVersionStr
    defaultConfig {
        applicationId "com.mrmichel.rustdroid_emu"
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

apply plugin: 'org.mozilla.rust-android-gradle.rust-android'

cargo {
    prebuiltToolchains = true
    verbose = true
    profile = 'release'
    module = "../../../platform/rustboyadvance-jni"
    targetDirectory = '../../../target'
    libname = "rustboyadvance_jni"
    targets = ['arm64', 'x86_64']
    apiLevel = 21
}

afterEvaluate {
    // The `cargoBuild` task isn't available until after evaluation.
    android.applicationVariants.all { variant ->
        def productFlavor = ""
        variant.productFlavors.each {
            productFlavor += "${it.name.capitalize()}"
        }
        def buildType = "${variant.buildType.name.capitalize()}"
        tasks["pre${productFlavor}${buildType}Build"].dependsOn(tasks["cargoBuild"])
    }
}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation "androidx.documentfile:documentfile:1.0.1"
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'commons-io:commons-io:2.16.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}
